// Tests that the types a writer adds are the types a reader recognises.

import Testing
import UttrflowCore

@Suite("The nspasteboard.org markers are written and read by one table")
struct PasteboardMarkersRoundTripTests {
    @Test(
        "reads back exactly the markers whose types were written",
        arguments: [
            PasteboardMarkers(), .concealed, .transient, .autoGenerated,
            [.concealed, .transient], [.concealed, .transient, .autoGenerated],
        ])
    func roundTrip(_ markers: PasteboardMarkers) {
        #expect(PasteboardMarkers(types: markers.typeIdentifiers) == markers)
    }

    @Test("writes one convention type per marker")
    func oneTypePerMarker() {
        let all: PasteboardMarkers = [.concealed, .transient, .autoGenerated]
        let expected = [
            "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ]
        #expect(all.typeIdentifiers == expected)
    }
}
