import Foundation
import Dispatch
import Synchronization
import Testing

@testable import UttrflowCore
@testable import UttrflowInput
import UttrflowTestSupport

/// A clipboard that records everything written to it and never touches the real one.
final class FakePasteboard: Pasteboard {
    private struct State {
        var text: String?
        var changeCount = 0
        var writes: [String] = []
        var concealed: [String] = []
        var markers: [String: String] = [:]
        var pictures: [Data] = []
        var acceptsWrites = true
        var onImageWrite: (@Sendable () -> Void)?
        var onTextWrite: (@Sendable (FakePasteboard) -> Void)?
    }

    private let state = Mutex(State())

    /// `acceptsWrites: false` models a clipboard that takes the write and then does not hold it.
    init(
        text: String? = nil, acceptsWrites: Bool = true,
        onImageWrite: (@Sendable () -> Void)? = nil,
        onTextWrite: (@Sendable (FakePasteboard) -> Void)? = nil
    ) {
        state.withLock { state in
            state.text = text
            state.acceptsWrites = acceptsWrites
            state.onImageWrite = onImageWrite
            state.onTextWrite = onTextWrite
        }
    }

    func text() -> String? { state.withLock(\.text) }
    func changeCount() -> Int? { state.withLock(\.changeCount) }

    func setText(_ text: String) {
        state.withLock { state in
            state.writes.append(text)
            state.changeCount += 1
            if state.acceptsWrites { state.text = text }
        }
    }

    func writeText(_ text: String, richText: String?) -> Int? {
        let (writeCount, onTextWrite) = state.withLock {
            state -> (Int, (@Sendable (FakePasteboard) -> Void)?) in
            state.writes.append(text)
            state.changeCount += 1
            if state.acceptsWrites { state.text = text }
            return (state.changeCount, state.onTextWrite)
        }
        onTextWrite?(self)
        return writeCount
    }

    func writeTransientText(_ text: String, richText: String?) -> Int? {
        let count = writeText(text, richText: richText)
        state.withLock { $0.markers[text] = "org.nspasteboard.TransientType" }
        return count
    }

    func writeAutoGeneratedText(_ text: String) -> Int? {
        let count = writeText(text, richText: nil)
        state.withLock { $0.markers[text] = "org.nspasteboard.AutoGeneratedType" }
        return count
    }

    /// A concealed write, which lands like any other and is also counted apart so a test can see the marker.
    func setConcealedText(_ text: String) {
        setText(text)
        state.withLock { $0.concealed.append(text) }
    }

    func writeConcealedText(_ text: String) -> Int? {
        let writeCount = writeText(text, richText: nil)
        state.withLock { $0.concealed.append(text) }
        return writeCount
    }

    /// K4 — a picture write, kept apart from the text ones so a test can tell them apart.
    func setImage(_ data: Data) {
        let onImageWrite = state.withLock { state -> (@Sendable () -> Void)? in
            state.pictures.append(data)
            state.changeCount += 1
            if state.acceptsWrites { state.text = nil }
            return state.onImageWrite
        }
        onImageWrite?()
    }

    /// Stands in for another app copying something while the paste is in flight.
    func copyFromAnotherApp(_ text: String) {
        state.withLock { state in
            state.text = text
            state.changeCount += 1
        }
    }

    var writes: [String] { state.withLock(\.writes) }
    var concealed: [String] { state.withLock(\.concealed) }
    var markers: [String: String] { state.withLock(\.markers) }
    var pictures: [Data] { state.withLock(\.pictures) }
}

/// A ⌘V that can be counted, and made to fail.
final class FakeKeystrokeSender: KeystrokeSender {
    private struct State {
        var pasteCount = 0
        var error: TextInsertionError?
        var onPaste: (@Sendable () -> Void)?
    }

    private let state = Mutex(State())

    /// `onPaste` runs inside `sendPaste`, between the engine writing the clipboard and reading it back.
    init(error: TextInsertionError? = nil, onPaste: (@Sendable () -> Void)? = nil) {
        state.withLock { state in
            state.error = error
            state.onPaste = onPaste
        }
    }

    func sendPaste() throws(TextInsertionError) {
        let (error, onPaste) = state.withLock {
            state -> (TextInsertionError?, (@Sendable () -> Void)?) in
            state.pasteCount += 1
            return (state.error, state.onPaste)
        }
        onPaste?()
        if let error { throw error }
    }

    var pasteCount: Int { state.withLock(\.pasteCount) }
}

/// A caret that answers a fixed value and counts how many times it was asked, which is the point of #222.
final class CountingFocus: AccessibilityFocus, @unchecked Sendable {
    private let answer: String
    private let readsBeforeItLands: Int
    private let reads = Mutex(0)

    /// `readsBeforeItLands` is how many reads answer something else, so a pre-paste read differs from the landed text.
    init(answer: String, readsBeforeItLands: Int = 0) {
        self.answer = answer
        self.readsBeforeItLands = readsBeforeItLands
    }

    func focusedTextField() -> (any FocusedTextField)? { nil }
    func hasFocusedElement() -> Bool { true }
    func isSelfFrontmost() -> Bool { false }

    func tail(upTo count: Int) -> FieldTail {
        let read = reads.withLock { reads -> Int in
            reads += 1
            return reads
        }
        return .text(read > readsBeforeItLands ? answer : "what was already there")
    }

    var readCount: Int { reads.withLock { $0 } }
}

/// Focus whose frontmost app can be flipped between `canInsert()` and `insert()`, modelling a switch to Uttrflow.
final class SwitchableFocus: AccessibilityFocus, @unchecked Sendable {
    private let selfIsFrontmost = Mutex(false)

    func focusedTextField() -> (any FocusedTextField)? { nil }
    func hasFocusedElement() -> Bool { true }
    func isSelfFrontmost() -> Bool { selfIsFrontmost.withLock { $0 } }
    func tail(upTo count: Int) -> FieldTail { .text("") }
    func frontmostApplication() -> InsertionDestination? { nil }
    func focusedFieldIsSecure() -> Bool { false }
    func precedingText(_ count: Int) -> String? { nil }

    /// Brings Uttrflow itself to the front, as the user would by switching to it.
    func becomeSelfFrontmost() { selfIsFrontmost.withLock { $0 = true } }
}

/// Returns frontmost apps in order so a test can switch targets at a specific insertion step.
private final class SequencedFrontmostFocus: AccessibilityFocus, @unchecked Sendable {
    private let applications: [InsertionDestination]
    private let index = Mutex(0)

    init(_ applications: [InsertionDestination]) { self.applications = applications }

    func focusedTextField() -> (any FocusedTextField)? { nil }
    func hasFocusedElement() -> Bool { true }
    func isSelfFrontmost() -> Bool { false }
    func frontmostApplication() -> InsertionDestination? {
        index.withLock { index in
            let application = applications[min(index, applications.count - 1)]
            index += 1
            return application
        }
    }
    func tail(upTo count: Int) -> FieldTail { .unreadable }
    func focusedFieldIsSecure() -> Bool { false }
}

/// Holds confirmation open after a paste is posted, so an overlapping insertion has somewhere to race.
private final class GatedConfirmationFocus: AccessibilityFocus, @unchecked Sendable {
    private let reads = Mutex(0)
    private let waiting = Mutex(false)
    private let continueConfirmation = DispatchSemaphore(value: 0)

    func focusedTextField() -> (any FocusedTextField)? { nil }
    func hasFocusedElement() -> Bool { true }
    func isSelfFrontmost() -> Bool { false }
    func tail(upTo count: Int) -> FieldTail {
        let read = reads.withLock { reads -> Int in
            reads += 1
            return reads
        }
        guard read == 2 else { return .text("previous text") }
        waiting.withLock { $0 = true }
        continueConfirmation.wait()
        return .text("first insertion")
    }
    var isWaitingForConfirmation: Bool { waiting.withLock { $0 } }

    func finishConfirmation() { continueConfirmation.signal() }
}

@Suite("PasteboardTextInsertionEngine")
struct PasteboardTextInsertionEngineTests {
    @Test("marks the paste route transient")
    func transientMarkerIsWrittenOnPaste() async throws {
        let pasteboard = FakePasteboard()
        let sut = PasteboardTextInsertionEngine(
            focus: FakeFocus(field: FakeTextField()), pasteboard: pasteboard,
            keystrokes: FakeKeystrokeSender())

        _ = try await sut.insert("dictated words")

        #expect(pasteboard.markers["dictated words"] == "org.nspasteboard.TransientType")
    }

    @Test("a panel paste skips reading another app's text field for a notice it will not show")
    func panelPasteDoesNotConfirmArrival() async throws {
        let focus = CountingFocus(answer: "inserted words")
        let sut = PasteboardTextInsertionEngine(
            focus: focus, pasteboard: FakePasteboard(), keystrokes: FakeKeystrokeSender(),
            confirmsArrival: false)

        let attempt = try await sut.insert("inserted words")

        #expect(attempt == .notReported)
        #expect(focus.readCount == 0)
    }

    private func engine(
        _ pasteboard: FakePasteboard,
        _ keystrokes: FakeKeystrokeSender,
        focus: any AccessibilityFocus = FakeFocus(field: FakeTextField())
    ) -> PasteboardTextInsertionEngine {
        PasteboardTextInsertionEngine(
            focus: focus, pasteboard: pasteboard, keystrokes: keystrokes)
    }

    @Test("independent coordinators sharing a pasteboard do not overlap confirmations")
    func independentCoordinatorsSerializePasteboardWrites() async throws {
        let pasteboard = FakePasteboard()
        let firstFocus = GatedConfirmationFocus()
        let firstEngine = PasteboardTextInsertionEngine(
            focus: firstFocus,
            pasteboard: pasteboard,
            keystrokes: FakeKeystrokeSender(),
            confirmation: PasteConfirmation(focus: firstFocus, clock: ScriptedClock()))
        let first = TextInsertionCoordinator(strategies: [firstEngine], focus: firstFocus)
        let firstTask = Task { try await first.insert("first insertion") }

        while !firstFocus.isWaitingForConfirmation { await Task.yield() }

        let secondFocus = FakeFocus()
        let waitingForGate = Signal()
        let secondEngine = PasteboardTextInsertionEngine(
            focus: secondFocus,
            pasteboard: pasteboard,
            keystrokes: FakeKeystrokeSender(),
            confirmation: PasteConfirmation(
                focus: secondFocus, clock: ScriptedClock()),
            onWaitingForGate: { waitingForGate.fire() })
        let second = TextInsertionCoordinator(strategies: [secondEngine], focus: secondFocus)
        let secondTask = Task { try await second.insert("second insertion") }

        try await arrival(of: waitingForGate.fired)
        #expect(pasteboard.writes == ["first insertion"], "the active confirmation still owns the pasteboard")

        firstFocus.finishConfirmation()
        _ = try await firstTask.value
        _ = try await secondTask.value
        #expect(pasteboard.writes == ["first insertion", "second insertion"])
    }

    /// Declining costs the user an insertion where trying costs nothing. See `Docs/input-paste-eligibility.md`.
    @Test("declines only when Uttrflow itself is in front")
    func declinesOnlyForItself() async {
        let elsewhere = engine(FakePasteboard(), FakeKeystrokeSender(), focus: FakeFocus(field: nil))
        #expect(await elsewhere.canInsert(), "nothing focused is still worth a try")

        let ourselves = engine(
            FakePasteboard(), FakeKeystrokeSender(), focus: FakeFocus(field: nil, isSelf: true))
        #expect(await ourselves.canInsert() == false, "must never paste into Uttrflow")
    }

    @Test("accepts when something is focused")
    func acceptsWithAFocusedField() async {
        #expect(await engine(FakePasteboard(), FakeKeystrokeSender()).canInsert())
    }

    /// The guard's whole point: eligibility answered for another app must not survive a switch to Uttrflow.
    @Test(
        "rejects the paste and leaves the clipboard alone when Uttrflow becomes frontmost after eligibility")
    func revalidatesFrontmostBeforeWriting() async {
        let focus = SwitchableFocus()
        let pasteboard = FakePasteboard()
        let keystrokes = FakeKeystrokeSender()
        let sut = engine(pasteboard, keystrokes, focus: focus)

        #expect(await sut.canInsert(), "another app is frontmost when eligibility is asked")
        focus.becomeSelfFrontmost()

        await #expect(throws: TextInsertionError.self) {
            try await sut.insert("private words")
        }

        #expect(pasteboard.writes.isEmpty, "the clipboard must not be touched once Uttrflow is frontmost")
        #expect(keystrokes.pasteCount == 0, "no paste may be posted into Uttrflow's own window")
    }

    @Test("does not change the clipboard when the captured app has already changed")
    func refusesChangedTargetBeforeClipboardWrite() async {
        let target = InsertionDestination(applicationName: "Editor", bundleIdentifier: "com.example.editor")
        let other = InsertionDestination(applicationName: "Browser", bundleIdentifier: "com.example.browser")
        let focus = SequencedFrontmostFocus([target, other])
        let pasteboard = FakePasteboard(text: "previous copy")
        let keystrokes = FakeKeystrokeSender()
        let sut = engine(pasteboard, keystrokes, focus: focus)

        await #expect(throws: TextInsertionError.insertionTargetChanged) {
            try await sut.insert("private words", targeting: target)
        }

        #expect(pasteboard.writes.isEmpty)
        #expect(pasteboard.text() == "previous copy")
        #expect(keystrokes.pasteCount == 0)
    }

    @Test("does not send paste when the destination changes immediately before the keystroke")
    func refusesChangedTargetBeforePaste() async {
        let target = InsertionDestination(applicationName: "Editor", bundleIdentifier: "com.example.editor")
        let other = InsertionDestination(applicationName: "Browser", bundleIdentifier: "com.example.browser")
        let focus = SequencedFrontmostFocus([target, target, other])
        let pasteboard = FakePasteboard()
        let keystrokes = FakeKeystrokeSender()
        let sut = engine(pasteboard, keystrokes, focus: focus)

        await #expect(throws: TextInsertionError.insertionTargetChanged) {
            try await sut.insert("private words", targeting: target)
        }

        #expect(pasteboard.writes == ["private words"])
        #expect(keystrokes.pasteCount == 0)
    }

    @Test("copies the text and presses paste exactly once")
    func pastesOnce() async throws {
        let pasteboard = FakePasteboard()
        let keystrokes = FakeKeystrokeSender()

        _ = try await engine(pasteboard, keystrokes).insert("hello there")

        #expect(pasteboard.writes.first == "hello there")
        #expect(keystrokes.pasteCount == 1)
    }

    /// The dictation stays put and the previous contents do not come back. See `Docs/insertion.md`.
    @Test("leaves the dictation on the clipboard rather than betting the paste landed")
    func keepsTheDictationOnTheClipboard() async throws {
        let paragraph = "A paragraph the user copied earlier and still needs."
        let pasteboard = FakePasteboard(text: paragraph)

        _ = try await engine(pasteboard, FakeKeystrokeSender()).insert("dictated words")

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == "dictated words")
    }

    /// Writing over a copy the user made since would be the same theft in the other direction.
    @Test("leaves a copy made since the paste exactly as it is")
    func leavesANewerCopyAlone() async throws {
        let pasteboard = FakePasteboard(text: "the old paragraph")
        let keystrokes = FakeKeystrokeSender(
            onPaste: { pasteboard.copyFromAnotherApp("something copied since") }
        )

        _ = try await engine(pasteboard, keystrokes).insert("dictated words")

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == "something copied since")
    }

    /// A clipboard holding an image reads as `nil` text, and inventing an empty one would erase it.
    @Test("keeps the words when the clipboard was not holding text")
    func keepsWordsWhenTheClipboardHeldNothing() async throws {
        let pasteboard = FakePasteboard(text: nil)

        _ = try await engine(pasteboard, FakeKeystrokeSender()).insert("dictated words")

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == "dictated words")
    }

    /// Where keeping the words matters most: the floor below would only put the same text back.
    @Test("keeps the words on the clipboard even when the keystroke is refused")
    func keepsWordsAfterFailedPaste() async {
        let pasteboard = FakePasteboard(text: "A paragraph the user copied earlier.")
        let keystrokes = FakeKeystrokeSender(error: .accessibilityDenied)
        let sut = engine(pasteboard, keystrokes)

        await #expect(throws: TextInsertionError.accessibilityDenied) {
            try await sut.insert("dictated words")
        }

        #expect(keystrokes.pasteCount == 1)
        #expect(pasteboard.text() == "dictated words", "the dictation must outlive the failure")
    }

    @Test("refuses to paste when the clipboard write does not stick")
    func refusesToPasteAnUnheldWrite() async {
        let pasteboard = FakePasteboard(text: "stale words", acceptsWrites: false)
        let keystrokes = FakeKeystrokeSender()
        let sut = engine(pasteboard, keystrokes)

        await #expect(throws: TextInsertionError.clipboardUnavailable) {
            try await sut.insert("dictated words")
        }

        #expect(keystrokes.pasteCount == 0, "a paste now would put the stale clipboard into the field")
    }

    @Test("stops fallback when another writer replaces the clipboard after the paste write")
    func doesNotOverwriteNewCopyDuringFallback() async {
        let copiedText = "the user's newer copy"
        let pasteboard = FakePasteboard(onTextWrite: { pasteboard in
            pasteboard.copyFromAnotherApp(copiedText)
        })
        let keystrokes = FakeKeystrokeSender()
        let focus = FakeFocus(field: FakeTextField())
        let paste = engine(pasteboard, keystrokes, focus: focus)
        let floor = ClipboardTextInsertionEngine(pasteboard: pasteboard)
        let coordinator = TextInsertionCoordinator(strategies: [paste, floor], focus: focus)

        await #expect(throws: TextInsertionError.clipboardChanged) {
            try await coordinator.insert("dictated words")
        }

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == copiedText)
        #expect(keystrokes.pasteCount == 0)
    }

    @Test("aborts when another app replaces the clipboard after verification")
    func abortsWhenClipboardChangesBeforePaste() async {
        let pasteboard = FakePasteboard(text: "previous words")
        let focus = CountingFocus(answer: "the field has not changed yet")
        // Models Universal Clipboard replacing the board during the off-main caret read.
        let countingFocus = InterleavingFocus(base: focus) {
            pasteboard.copyFromAnotherApp("copied from another device")
        }
        let keystrokes = FakeKeystrokeSender()
        let sut = engine(pasteboard, keystrokes, focus: countingFocus)

        await #expect(throws: TextInsertionError.clipboardChanged) {
            try await sut.insert("dictated words")
        }

        #expect(pasteboard.text() == "copied from another device")
        #expect(keystrokes.pasteCount == 0, "Cmd+V must not paste the interloping clipboard contents")
    }

    @Test("copies an empty transcript without inventing anything")
    func emptyText() async throws {
        let pasteboard = FakePasteboard(text: "previous")

        _ = try await engine(pasteboard, FakeKeystrokeSender()).insert("")

        #expect(pasteboard.writes == [""])
    }

    @Test("reports itself as the pasteboard method")
    func method() {
        let sut = engine(FakePasteboard(), FakeKeystrokeSender())
        #expect(sut.method == .pasteboard)
    }

    /// The engine under a caret that answers, with the wait driven by a clock the test owns.
    private func confirming(
        _ focus: CountingFocus, reporting: (@Sendable (PasteConfirmation.Outcome) -> Void)? = nil
    ) -> PasteboardTextInsertionEngine {
        PasteboardTextInsertionEngine(
            focus: focus, pasteboard: FakePasteboard(), keystrokes: FakeKeystrokeSender(),
            confirmation: PasteConfirmation(focus: focus, clock: ScriptedClock()),
            reporting: reporting)
    }

    /// #222: the call was optional-chained behind the reporter, so attaching a logger switched it on.
    @Test("waits for the paste even when nothing is listening for the answer")
    func confirmsWithNoReporterAttached() async throws {
        let focus = CountingFocus(answer: "and then dictated words")

        _ = try await confirming(focus).insert("dictated words")

        #expect(
            focus.readCount > 0,
            "whether a logger is attached must not decide whether the paste is checked")
    }

    /// #222: the answer reached only the optional closure, so nothing upstream could act on it.
    @Test("reports a paste it never saw arrive as unconfirmed rather than as inserted")
    func reportsAnUnconfirmedPaste() async throws {
        let focus = CountingFocus(answer: "something else entirely")

        #expect(try await confirming(focus).insert("dictated words") == .unconfirmed)
    }

    @Test("reports a paste it read back as confirmed")
    func reportsAConfirmedPaste() async throws {
        let focus = CountingFocus(answer: "and then dictated words", readsBeforeItLands: 1)

        #expect(try await confirming(focus).insert("dictated words") == .confirmed)
    }

    /// A field that will not say what it holds proves nothing, which is most of them.
    @Test("proves nothing about a field that will not report what it holds")
    func reportsNothingForAnUnreadableField() async throws {
        let sut = engine(FakePasteboard(), FakeKeystrokeSender(), focus: FakeFocus(field: nil))

        #expect(try await sut.insert("dictated words") == .notReported)
    }

    /// The reporter stays an observer: it still sees every answer, and decides none of them.
    @Test("still hands the answer to a reporter that is attached")
    func reportsToAnAttachedLogger() async throws {
        let seen = Mutex<[PasteConfirmation.Outcome]>([])
        let focus = CountingFocus(answer: "and then dictated words")

        _ = try await confirming(focus, reporting: { outcome in seen.withLock { $0.append(outcome) } })
            .insert("dictated words")

        #expect(seen.withLock { $0.count } == 1)
    }
}

/// Runs an interleaving when the engine crosses into the AX caret read.
private final class InterleavingFocus: AccessibilityFocus, @unchecked Sendable {
    private let base: any AccessibilityFocus
    private let onTail: @Sendable () -> Void
    private let didInterleave = Mutex(false)

    init(base: any AccessibilityFocus, onTail: @escaping @Sendable () -> Void) {
        self.base = base
        self.onTail = onTail
    }

    func focusedTextField() -> (any FocusedTextField)? { base.focusedTextField() }
    func hasFocusedElement() -> Bool { base.hasFocusedElement() }
    func isSelfFrontmost() -> Bool { base.isSelfFrontmost() }
    func tail(upTo count: Int) -> FieldTail {
        let shouldInterleave = didInterleave.withLock { didInterleave -> Bool in
            guard !didInterleave else { return false }
            didInterleave = true
            return true
        }
        if shouldInterleave { onTail() }
        return base.tail(upTo: count)
    }
    func frontmostApplication() -> InsertionDestination? { base.frontmostApplication() }
    func focusedFieldIsSecure() -> Bool { base.focusedFieldIsSecure() }
    func precedingText(_ count: Int) -> String? { base.precedingText(count) }
}

@Suite("PasteboardImageInsertionEngine")
struct PasteboardImageInsertionEngineTests {
    @Test("rechecks the frontmost application after writing the image")
    func rechecksFrontmostAfterWritingImage() async {
        let imageData = await Task.detached { Data([0x89, 0x50, 0x4E, 0x47]) }.value
        let focus = SwitchableFocus()
        let pasteboard = FakePasteboard(onImageWrite: { focus.becomeSelfFrontmost() })
        let keystrokes = FakeKeystrokeSender()
        let sut = PasteboardImageInsertionEngine(
            focus: focus, pasteboard: pasteboard, keystrokes: keystrokes)

        #expect(throws: TextInsertionError.self) { try sut.insert(imageData) }
        #expect(pasteboard.pictures == [imageData])
        #expect(keystrokes.pasteCount == 0, "a rejected image must not post ⌘V")
    }

    @Test("does not replace the clipboard when Uttrflow is already frontmost")
    func refusesBeforeWritingWhenUttrflowIsFrontmost() {
        let focus = SwitchableFocus()
        focus.becomeSelfFrontmost()
        let pasteboard = FakePasteboard()
        let keystrokes = FakeKeystrokeSender()
        let sut = PasteboardImageInsertionEngine(
            focus: focus, pasteboard: pasteboard, keystrokes: keystrokes)

        #expect(throws: TextInsertionError.self) { try sut.insert(Data([0x89, 0x50])) }
        #expect(pasteboard.pictures.isEmpty)
        #expect(keystrokes.pasteCount == 0)
    }

    @Test("writes and pastes an image while another application is frontmost")
    func pastesImageToExternalApplication() throws {
        let imageData = Data([0x89, 0x50, 0x4E, 0x47])
        let pasteboard = FakePasteboard()
        let keystrokes = FakeKeystrokeSender()
        let sut = PasteboardImageInsertionEngine(
            focus: SwitchableFocus(), pasteboard: pasteboard, keystrokes: keystrokes)

        try sut.insert(imageData)

        #expect(pasteboard.pictures == [imageData])
        #expect(keystrokes.pasteCount == 1)
    }
}

@Suite("The route that is assembled without a logger")
struct UnreportedPasteRouteTests {
    /// #222: the clip route is built with no `reporting:`, so it was the one path that checked nothing.
    @Test("checks the paste on the route that nothing is listening to")
    func confirmsWithoutAReporter() async throws {
        let focus = CountingFocus(answer: "and then dictated words", readsBeforeItLands: 1)
        let coordinator = TextInsertion.coordinator(
            focus: focus, pasteboard: FakePasteboard(), keystrokes: FakeKeystrokeSender())

        let attempt = try await coordinator.insert("dictated words")

        #expect(attempt == InsertionAttempt(.pasteboard, arrival: .confirmed))
        #expect(focus.readCount > 0, "how the route is composed must not decide what it verifies")
    }

    @Test("a clipboard-free route types after Accessibility and paste refuse")
    func clipboardFreeRouteUsesTypingInsteadOfReplacingTheClipboard() async throws {
        let pasteboard = FakePasteboard(text: "the user's copy")
        let typist = PanelRouteTypist()
        let coordinator = TextInsertion.coordinator(
            focus: FakeFocus(field: nil), pasteboard: pasteboard,
            keystrokes: FakeKeystrokeSender(error: .accessibilityDenied), typist: typist,
            confirmsArrival: false, clipboardFallback: false)

        let attempt = try await coordinator.insert("a panel clip")

        #expect(attempt.method == .typed)
        #expect(typist.text == ["a panel clip"])
        #expect(pasteboard.text() == "the user's copy")
        #expect(pasteboard.writes.isEmpty)
    }
}

private final class PanelRouteTypist: KeystrokeTyping, @unchecked Sendable {
    private let lock = NSLock()
    private var values: [String] = []
    var text: [String] {
        lock.lock()
        defer { lock.unlock() }
        return values
    }
    func type(_ text: String) throws(TextInsertionError) {
        lock.lock()
        values.append(text)
        lock.unlock()
    }
    func deleteBackwards(_ count: Int) throws(TextInsertionError) {}
    func canType(_ text: String) -> Bool { true }
}

@Suite("Clipboard-free dictation insertion")
struct ClipboardFreeDictationInsertionTests {
    @Test("uses Accessibility then typing and never borrows or writes the clipboard")
    func routeLeavesClipboardAlone() async throws {
        let pasteboard = FakePasteboard(text: "the user's copy")
        let typist = RouteRecordingTypist()
        let coordinator = TextInsertion.dictation(focus: FakeFocus(field: nil), typist: typist)

        #expect(coordinator.route == [.accessibility, .typed])
        let attempt = try await coordinator.insert("dictated words")

        #expect(attempt.method == .typed)
        #expect(typist.text == ["dictated words"])
        #expect(pasteboard.text() == "the user's copy")
        #expect(pasteboard.writes.isEmpty)
    }

    @Test("the named dictation route contains no pasteboard strategy")
    func routeIsAccessibilityThenTyping() {
        #expect(TextInsertion.dictation().route == [.accessibility, .typed])
    }

    @Test("refused typing becomes a truthful copy action instead of a clipboard claim")
    func refusesWithoutReplacingClipboard() async {
        let coordinator = TextInsertion.dictation(
            focus: FakeFocus(field: nil),
            typist: RouteRecordingTypist(error: .insertionRejected(description: "unsupported character")))

        await #expect(
            throws: TextInsertionError.insertionNeedsCopy(
                description: TextInsertionError.insertionRejected(
                    description: "unsupported character"
                ).userMessage)
        ) {
            try await coordinator.insert("dictated words")
        }
    }
}

private final class RouteRecordingTypist: KeystrokeTyping, @unchecked Sendable {
    private let lock = NSLock()
    private var values: [String] = []
    private let error: TextInsertionError?
    init(error: TextInsertionError? = nil) { self.error = error }
    var text: [String] {
        lock.lock()
        defer { lock.unlock() }
        return values
    }
    func type(_ text: String) throws(TextInsertionError) {
        if let error { throw error }
        lock.lock()
        values.append(text)
        lock.unlock()
    }
    func deleteBackwards(_ count: Int) throws(TextInsertionError) {}
    func canType(_ text: String) -> Bool { true }
}

@Suite("ClipboardTextInsertionEngine")
struct ClipboardTextInsertionEngineTests {
    @Test("marks the clipboard floor as generated while ordinary copies stay unmarked")
    func generatedMarkerIsSpecificToTheInsertionFloor() async throws {
        let pasteboard = FakePasteboard()
        _ = try await ClipboardTextInsertionEngine(pasteboard: pasteboard).insert("dictated words")

        #expect(pasteboard.markers["dictated words"] == "org.nspasteboard.AutoGeneratedType")
        pasteboard.setText("user copied words")
        #expect(pasteboard.markers["user copied words"] == nil)
    }

    @Test("leaves the text on the clipboard for the user to paste")
    func setsTheText() async throws {
        let pasteboard = FakePasteboard(text: "previous")
        _ = try await ClipboardTextInsertionEngine(pasteboard: pasteboard).insert("dictated words")

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == "dictated words")
    }

    /// Claiming success after a write that did not stick would lose the words silently.
    @Test("reports the clipboard as unavailable when the write does not stick")
    func failedWrite() async {
        let pasteboard = FakePasteboard(acceptsWrites: false)
        let sut = ClipboardTextInsertionEngine(pasteboard: pasteboard)

        await #expect(throws: TextInsertionError.clipboardUnavailable) {
            try await sut.insert("dictated words")
        }
    }

    @Test("preserves a newer copy when the clipboard floor loses ownership")
    func preservesNewCopyAfterFloorWrite() async {
        let copiedText = "the user's newer copy"
        let pasteboard = FakePasteboard(onTextWrite: { pasteboard in
            pasteboard.copyFromAnotherApp(copiedText)
        })

        await #expect(throws: TextInsertionError.clipboardChanged) {
            try await ClipboardTextInsertionEngine(pasteboard: pasteboard).insert("dictated words")
        }

        #expect(pasteboard.writes == ["dictated words"])
        #expect(pasteboard.text() == copiedText)
    }

    @Test("copies an empty transcript without complaining")
    func emptyText() async throws {
        let pasteboard = FakePasteboard()
        _ = try await ClipboardTextInsertionEngine(pasteboard: pasteboard).insert("")

        #expect(pasteboard.text() == "")
    }

    /// Not `.pasteboard`: that value means a paste landed, this one that the words are waiting.
    @Test("reports itself as the clipboard method, not a completed paste")
    func method() {
        #expect(ClipboardTextInsertionEngine(pasteboard: FakePasteboard()).method == .clipboard)
    }

    /// This is the last resort in the fallback chain, so it must never decline.
    @Test("is always available, because a clipboard always is")
    func alwaysCanInsert() async {
        #expect(await ClipboardTextInsertionEngine(pasteboard: FakePasteboard()).canInsert())
    }
}
