import AppKit
import Testing

@testable import UttrflowInput

@Suite("Dictation pasteboard markers")
struct PasteboardMarkerWriteTests {
    @Test("puts the transient marker beside the same text and rich text item")
    func transientMarkerSharesThePasteboardItem() {
        let item = SystemPasteboard.textItem(
            "dictated words", richText: "<b>dictated words</b>",
            marker: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))

        #expect(item.string(forType: .string) == "dictated words")
        #expect(item.string(forType: .html) == "<b>dictated words</b>")
        #expect(item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")))
    }

    @Test("puts the generated marker beside clipboard-floor text")
    func generatedMarkerSharesThePasteboardItem() {
        let item = SystemPasteboard.textItem(
            "dictated words", richText: nil,
            marker: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))

        #expect(item.string(forType: .string) == "dictated words")
        #expect(item.types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")))
    }

    @Test("leaves ordinary user copies unmarked")
    func ordinaryCopyHasNoMarker() {
        let item = SystemPasteboard.textItem("user copied words", richText: nil)

        #expect(item.string(forType: .string) == "user copied words")
        #expect(!item.types.contains { $0.rawValue.hasPrefix("org.nspasteboard.") })
    }
}
